### ISSUE TITLE
https compatible links

### ISSUE THREAD

**Issue by dervondenbergen** [bullgit/wizz.css#1]
please change all urls to be https compatible, otherwise the layout will not be as excepted

@LukyVj @Haroenv

**Comment by LukyVj** [comment]
?

**Comment by LukyVj** [comment]
@dervondenbergen It works just fine ? Which urls are you talking about ?

**Comment by dervondenbergen** [comment]
https://github.com/bullgit/wizz.css/blob/gh-pages/index.html#L15-L16

**Comment by dervondenbergen** [comment]
maybe you don't want to change it, and i tagged you as you created this project

**Comment by LukyVj** [comment]
![](http://puu.sh/kl9QV/253f64a8e4.png)

**Comment by LukyVj** [comment]
it's fine I think 
( and dunno where the index is )

**Comment by Haroenv** [comment]
in `gh-pages` I guess?
